
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module cpt_sys(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// Seg7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// VGA //////////
	output		          		VGA_BLANK_N,
	output		     [7:0]		VGA_B,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS,

	//////////// PS2 //////////
	inout 		          		PS2_CLK,
	inout 		          		PS2_CLK2,
	inout 		          		PS2_DAT,
	inout 		          		PS2_DAT2
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

wire [31:0]data;
wire [31:0]data2;
cpu cpu_v1(
	.clk(~KEY[0]),
	.regaddr(SW[4:0]),
	.regdata(data),
	.data(data2)
);
hex hex1(data[3:0],HEX0);
hex hex2(data[7:4],HEX1);
hex hex3(data[11:8],HEX2);
hex hex4(data[15:12],HEX3);
hex hex5(data2[3:0],HEX4);
hex hex6(data2[7:4],HEX5);



//=======================================================
//  Structural coding
//=======================================================



endmodule
